#!/bin/sh

#DEBUG=1
VERBOSE=1
# . /etc/network/nets
. /etc/network/fwlib

fw_init
$ADD INPUT $DROP   $STATE_I
$ADD INPUT $ACCEPT $STATE_ER
$ADD INPUT $ACCEPT $TCP --dport 22
$ADD INPUT $ACCEPT $ICMP
# $ADD INPUT $DROPLOG
$ADD INPUT $ACCEPT
    
# $INS POSTROUTING -t nat -s 192.168.1.0/24 $SNAT --to-source r.e.a.l
$ADD FORWARD $DROPLOG

